import type { Metadata } from 'next';

export const metadata: Metadata = {
  metadataBase: new URL('https://www.mindgleam.app'),
  title: 'MindGleam - AI Mental Wellness App | Affordable CBT Therapy Alternative | Free Trial',
  description: 'AI-powered mental wellness companion offering personalized CBT guidance at $4.99/month. Get 20 free messages, mood tracking, and 24/7 support. Affordable alternative to traditional therapy.',
  keywords: [
    'AI mental health app',
    'affordable therapy alternative',
    'CBT app under $5',
    'mental wellness app free trial',
    'AI counseling chatbot',
    'personalized mental health support',
    'anxiety management app',
    'depression support app',
    'mood tracking and analysis',
    'thought pattern coaching',
    'cognitive behavioral therapy app',
    'mental health companion app',
    '24/7 mental wellness support',
    'AI therapy assistant',
    'emotional wellness tracker',
    'mindfulness and CBT app',
    'mental health self-help tools',
    'AI psychological guidance',
    'stress management app',
    'mental wellness journaling',
    'affordable mental health care',
    'headspace alternative',
    'calm app alternative',
    'betterhelp alternative'
  ],
  viewport: 'width=device-width, initial-scale=1',
  openGraph: {
    title: 'MindGleam - Affordable AI Mental Wellness | $4.99/month vs $240+ for therapy',
    description: 'Get personalized CBT guidance, mood tracking, and 24/7 AI support for just $4.99/month. Start with 20 free messages. Affordable alternative to expensive therapy apps.',
    images: ['/android-chrome-512x512.png'],
    type: 'website',
    url: 'https://www.mindgleam.app',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'MindGleam - AI Mental Wellness for $4.99/month',
    description: 'Affordable AI-powered mental wellness with CBT guidance. 20 free messages to start. Better value than Headspace, Calm, or BetterHelp.',
    images: ['/android-chrome-512x512.png'],
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '32x32', type: 'image/x-icon' },
      { url: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
    shortcut: '/favicon.ico',
  },
  robots: {
    index: true,
    follow: true,
  },
  category: 'Health & Wellness',
}; 